# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 11 Nov 2014 16:12:05 +0000
*	@ALL	0
*	@monitor	1
*	@user	8
operation:monitoring:*	ink	1
public:*	@ALL	1
public:*	@user	8
start	@ALL	1
