<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 27 Jul 2018 10:16:17 +0200
 */

$conf['title'] = 'Cyclops HMS';
$conf['lang'] = 'es';
$conf['template'] = 'arctic';
$conf['license'] = 'publicdomain';
$conf['dmode'] = 0770;
$conf['fmode'] = 0660;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['jpg_quality'] = 100;
$conf['fetchsize'] = 1024000;
$conf['dnslookups'] = 0;
$conf['proxy']['port'] = 3128;
$conf['proxy']['pass'] = '<b>aW5pY2lhbDE=';
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['snow']['enabled'] = 0;
$conf['plugin']['tools']['show_link'] = '2';
$conf['plugin']['odt']['css_template'] = 'arctic';
$conf['plugin']['wikicalendar']['timezone'] = 'Europe/Madrid';
$conf['tpl']['arctic']['sidebar'] = 'none';
$conf['tpl']['arctic']['main_sidebar_always'] = 0;
$conf['tpl']['arctic']['search'] = 'right';
$conf['tpl']['arctic']['closedwiki'] = 1;
$conf['tpl']['arctic']['hideactions'] = 1;
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cyborg';
$conf['tpl']['zenlike']['hideTools'] = '1';
$conf['tpl']['mnml-blog']['mnmlblog_sidebarnav'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_copyright'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_copyright_default'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_search'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_qrcodebox'] = '0';
$conf['tpl']['dokubootstrapsimplified']['bootswatch'] = 'united';
$conf['tpl']['dokubook']['sb_pagename'] = 'sidebar';
$conf['tpl']['dokubook']['closedwiki'] = '1';
$conf['tpl']['dokuwikitemplatedokubrickmaster']['sidebar_content'] = 'toc,main,user,group,namespace,index';
$conf['tpl']['scanlines']['sidebar'] = 'none';
$conf['tpl']['scanlines']['main_sidebar_always'] = '0';
$conf['tpl']['scanlines']['left_sidebar_content'] = 'main,toc,index,extra';
$conf['tpl']['scanlines']['right_sidebar_content'] = 'main,toc,index,extra';
$conf['tpl']['scanlines']['sitemap'] = '0';
$conf['tpl']['scanlines']['top_link'] = '0';

// end auto-generated content
