#### INCLUDE VARS TO DEFINE USER PROFILE ####
#### INDICATE PROFILE NAME HERE ####
#_profile_name='PROFILE NAME'
#_par_uid='USERS INIT UID'
#_par_gid='DEFAULT GROUP ID'
#_par_des='DEFAULT USER DESCRIPTION'
#_par_home='DEFAULT USER HOME'
#_par_pass='DEFAULT USER PASSWORD'
#_opt_nis='yes/no' ## ENABLE NIS USER AUTH
#_par_slurm='DEFAULT SLURM ACCOUNT' ## THIS OPTION ENABLE SLURM USER
#_par_lustre='yes/no' ## ENABLE LUSTRE ACCESS
